site_name: BreweryX
site_author: Jsinco, szarkan

repo_url: https://github.com/Jsinco/BreweryX

theme:
  language: en
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: indigo
  features:
    - content.tabs.link
 #   - navigation.instant
  #  - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - toc.follow
    - content.action.edit
  logo: assets/favicon.jpg
  favicon: assets/favicon.jpg
  font:
    text: Inter
    code: Fira Code
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - pymdownx.critic
  - pymdownx.snippets:
      auto_append:
        - includes/links.md
  - toc:
      permalink: "#"
      separator: "_"
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - def_list
  - md_in_html
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
  - stylesheets/my.css
plugins:
  - open-in-new-tab
  - search:
      lang: en
  - minify:
      minify_html: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          default: false
          name: Русский
          build: true
extra:
  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: Русский
  #     link: /ru/
  #     lang: ru
  status:
    new: Recently updated!
    inprogress: Article is in progress
  social:
    - icon: simple/discord
      link: https://discord.gg/3FkNaNDnta
      name: Discord
    - icon: simple/github
      link: https://github.com/Jsinco/BreweryX
      name: Github
nav:
  - '': index.md
  - Documentation:
    - Config:
      - en/guide/recipies.md
      - en/guide/edit_config.md
      - en/guide/default_config.md
    - Other:
      - en/guide/brewing_guide.md
      - en/guide/custom_items.md
  - API:
    - en/api/api.md
    - en/api/depenizen.md